//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapprochBySP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarshipData
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual StudentData StudentData { get; set; }
    }
}
