//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapprochBySP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentData()
        {
            this.ScholarshipDatas = new HashSet<ScholarshipData>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int RollNo { get; set; }
        public string Class { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarshipData> ScholarshipDatas { get; set; }
    }
}
